In [1]:
!test -f test6.grib || wget https://github.com/ecmwf/emohawk/raw/main/docs/examples/test6.grib

## Inspecting GRIB contents

We load a GRIB file containing 6 messages:

In [2]:
import emohawk

fs = emohawk.load_from("file", "test6.grib")

### Using ls()

In [3]:
fs.ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,t,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll
1,ecmf,u,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll
2,ecmf,v,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll
3,ecmf,t,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
4,ecmf,u,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll
5,ecmf,v,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll

We can add extra keys:

In [4]:
fs.ls(extra_keys=["paramId"])

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType,paramId
0,ecmf,t,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll,130
1,ecmf,u,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll,131
2,ecmf,v,isobaricInhPa,1000,20180801,1200,0,an,0,regular_ll,132
3,ecmf,t,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll,130
4,ecmf,u,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll,131
5,ecmf,v,isobaricInhPa,850,20180801,1200,0,an,0,regular_ll,132

### Using describe

We can describe the whole object:

In [5]:
fs.describe()

We can also describe a given parameter (defined by shortName or paramId):

In [6]:
fs.describe("t")

In [7]:
fs.describe(131)

### Inspecting individual field metadata

In [8]:
fs[0].as_mars()

{'domain': 'g',
 'levtype': 'pl',
 'levelist': 1000,
 'date': 20180801,
 'time': 1200,
 'step': 0,
 'param': 't',
 'class': 'od',
 'type': 'an',
 'stream': 'oper',
 'expver': '0001'}

In [9]:
fs[0].metadata(namespace="mars")

{'domain': 'g',
 'levtype': 'pl',
 'levelist': 1000,
 'date': 20180801,
 'time': 1200,
 'step': 0,
 'param': 't',
 'class': 'od',
 'type': 'an',
 'stream': 'oper',
 'expver': '0001'}

### Inspecting all the namespace keys for a message

info() gives a tabbed interface to inspect the various namespaces:

In [10]:
fs[0].info()

For performance reasons the "statistics" namespace has to be accessed separately:

In [11]:
fs[1].info(namespace="statistics")

HTML formatting can be switched off:

In [12]:
fs[1].info(namespace="mars", html=False)

{'mars': {'domain': 'g',
  'levtype': 'pl',
  'levelist': 1000,
  'date': 20180801,
  'time': 1200,
  'step': 0,
  'param': 'u',
  'class': 'od',
  'type': 'an',
  'stream': 'oper',
  'expver': '0001'}}